research_task:
  description: >
    Scan the market for top 10 high-momentum coins. Provide symbols and buy thesis and check the ticker price using the ticker price tool to validate the coin is out on bybit
  expected_output: >
    A summarized list of 10 tickers with specific reasons for investment in markdown format.
  agent: researcher

analysis_task:
  description: >
    Check the current price of the coins and perform analysis to determine if they in a good buy zone using mathematical calculations to provide a RSI and MACD to be used by the strategist in determining the buy or sell condition
  expected_output: >
    The RSI and MACD of selected coins
  agent: analyst

strategist_task:
  description: >
    Determine the buy or sell condition using the information provided from the analysis and also ascertain the amount to buy or sell to maximize profit as much as possible due to the confidence rate of the calculation, determine the stop loss to 1% and use a take profit of 2%
  expected_output: >
    Execution report with Bybit Order IDs for each trade in markdown format.
  agent: strategist

trade_task:
  description: >
    Take the trade orders from the strategist and execute them using the execute multiple order tool. Always check wallet balance before executing any trade and abort if funds are insufficient. After execution, provide a report with the Bybit Order IDs for each trade.
  expected_output: >
    Execution report with Bybit Order IDs for each trade in markdown format.
  agent: trader

report_task:
  description: >
    Provide a clear and concise report of the executed trades in a markdown format with the Bybit Order IDs for each trade. The report should include the coins that were traded, the amount that was traded, the price at which the trade was executed, the stop loss and take profit levels that were set for the trade, and the Bybit Order IDs for each trade.
  expected_output: >
    A markdown report summarizing the executed trades with all necessary details.
  agent: reporter
